name: Build ADK Web Prompt Copy Extension

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
      - run: bun run zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adk-web-prompt-copy-build
          path: |
            .output/**
            *.zip
          retention-days: 30
          include-hidden-files: true

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Get package version
        id: package_version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .output/adk-web-prompt-copy-${{ steps.package_version.outputs.version }}-chrome.zip
          asset_name: adk-web-prompt-copy-${{ steps.package_version.outputs.version }}-chrome.zip
          asset_content_type: application/zip